2020-05-17 10:37:36,525:INFO:/home/shiro/djangoproject/IDC/datalabel/forms.py changed, reloading.
2020-05-17 10:40:51,366:INFO:/home/shiro/djangoproject/IDC/datalabel/views.py changed, reloading.
2020-05-17 10:41:01,148:INFO:/home/shiro/djangoproject/IDC/datalabel/views.py changed, reloading.
2020-05-17 10:41:29,569:INFO:/home/shiro/djangoproject/IDC/datalabel/tasks.py changed, reloading.
2020-05-17 10:41:41,670:INFO:/home/shiro/djangoproject/IDC/datalabel/views.py changed, reloading.
2020-05-17 10:43:28,170:INFO:/home/shiro/djangoproject/IDC/datalabel/tasks.py changed, reloading.
2020-05-17 10:56:49,967:INFO:/home/shiro/djangoproject/IDC/datalabel/tasks.py changed, reloading.
2020-05-17 11:03:03,565:INFO:/home/shiro/djangoproject/IDC/datalabel/tasks.py changed, reloading.
2020-05-17 11:03:53,586:INFO:/home/shiro/djangoproject/IDC/datalabel/tasks.py changed, reloading.
2020-05-17 11:04:46,694:INFO:/home/shiro/djangoproject/IDC/datalabel/tasks.py changed, reloading.
2020-05-17 11:05:36,258:INFO:/home/shiro/djangoproject/IDC/datalabel/views.py changed, reloading.
2020-05-17 11:17:54,006:INFO:/home/shiro/djangoproject/IDC/datalabel/tasks.py changed, reloading.
2020-05-17 11:25:08,818:INFO:/home/shiro/djangoproject/IDC/datalabel/tasks.py changed, reloading.
2020-05-17 11:31:11,855:INFO:/home/shiro/djangoproject/IDC/datalabel/tasks.py changed, reloading.
2020-05-17 11:31:19,644:INFO:/home/shiro/djangoproject/IDC/datalabel/tasks.py changed, reloading.
2020-05-17 11:33:56,554:INFO:/home/shiro/djangoproject/IDC/datalabel/dboperations.py changed, reloading.
2020-05-17 11:34:05,429:INFO:/home/shiro/djangoproject/IDC/datalabel/tasks.py changed, reloading.
2020-05-17 11:34:15,485:INFO:/home/shiro/djangoproject/IDC/datalabel/views.py changed, reloading.
2020-05-17 11:35:39,325:INFO:/home/shiro/djangoproject/IDC/datalabel/tasks.py changed, reloading.
2020-05-17 18:16:05,358:INFO:/home/shiro/djangoproject/IDC/datalabel/tasks.py changed, reloading.
2020-05-17 18:17:53,726:INFO:/home/shiro/djangoproject/IDC/datalabel/dboperations.py changed, reloading.
2020-05-17 18:18:37,072:WARNING:Not Found: /favicon.ico
2020-05-17 18:20:31,133:INFO:/home/shiro/djangoproject/IDC/datalabel/dboperations.py changed, reloading.
2020-05-17 18:23:44,699:INFO:/home/shiro/djangoproject/IDC/datalabel/dboperations.py changed, reloading.
2020-05-17 18:23:47,987:INFO:/home/shiro/djangoproject/IDC/datalabel/dboperations.py changed, reloading.
2020-05-17 18:25:28,704:WARNING:Not Found: /favicon.ico
2020-05-17 18:31:03,665:INFO:/home/shiro/djangoproject/IDC/datalabel/dboperations.py changed, reloading.
2020-05-19 16:57:21,889:WARNING:Not Found: /favicon.ico
2020-05-20 21:15:43,736:WARNING:Not Found: /favicon.ico
2020-05-20 21:20:02,153:ERROR:Internal Server Error: /datalabel/project/9/
Traceback (most recent call last):
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/shiro/djangoproject/IDC/datalabel/views.py", line 38, in projectDetail
    return render(request, 'datalabel/projectdetail.html', context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/urls/resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'getNextItem' not found. 'getNextItem' is not a valid view function or pattern name.
2020-05-20 21:20:06,890:ERROR:Internal Server Error: /datalabel/project/9/
Traceback (most recent call last):
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/shiro/djangoproject/IDC/datalabel/views.py", line 38, in projectDetail
    return render(request, 'datalabel/projectdetail.html', context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/urls/resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'getNextItem' not found. 'getNextItem' is not a valid view function or pattern name.
2020-05-20 21:20:07,128:WARNING:Not Found: /favicon.ico
2020-05-20 21:20:11,146:ERROR:Internal Server Error: /datalabel/project/8/
Traceback (most recent call last):
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/shiro/djangoproject/IDC/datalabel/views.py", line 38, in projectDetail
    return render(request, 'datalabel/projectdetail.html', context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/urls/resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'getNextItem' not found. 'getNextItem' is not a valid view function or pattern name.
2020-05-20 21:21:01,177:ERROR:Internal Server Error: /datalabel/project/9/
Traceback (most recent call last):
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/shiro/djangoproject/IDC/datalabel/views.py", line 38, in projectDetail
    return render(request, 'datalabel/projectdetail.html', context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/urls/resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'getNextItem' not found. 'getNextItem' is not a valid view function or pattern name.
2020-05-20 21:24:16,813:ERROR:Internal Server Error: /datalabel/getNextItem/
Traceback (most recent call last):
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/shiro/djangoproject/IDC/datalabel/views.py", line 57, in getNextItem
    return render(request, 'datalabel/labelitem.html', context)
NameError: name 'context' is not defined
2020-07-13 21:30:31,421:WARNING:Not Found: /labelingProject/IDC
2020-07-13 21:30:32,141:WARNING:Not Found: /favicon.ico
2020-07-13 21:31:11,510:ERROR:Database connection error
2020-07-13 21:31:11,633:ERROR:Internal Server Error: /datalabel/labelingProject/IDC
Traceback (most recent call last):
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/shiro/djangoproject/IDC/datalabel/views.py", line 43, in labelingProject
    qTable, categoryList = get_table(tableName=projectName)
  File "/home/shiro/djangoproject/IDC/datalabel/dboperations.py", line 15, in with_connection_
    rv = func(conn, *args, **kwargs)
  File "/home/shiro/djangoproject/IDC/datalabel/dboperations.py", line 55, in get_table
    WHERE projectName = {tableName}""")
sqlite3.OperationalError: no such table: requestForm
2020-07-13 21:31:23,926:ERROR:Database connection error
2020-07-13 21:31:24,000:ERROR:Internal Server Error: /datalabel/labelingProject/test
Traceback (most recent call last):
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/shiro/djangoproject/IDC/datalabel/views.py", line 43, in labelingProject
    qTable, categoryList = get_table(tableName=projectName)
  File "/home/shiro/djangoproject/IDC/datalabel/dboperations.py", line 15, in with_connection_
    rv = func(conn, *args, **kwargs)
  File "/home/shiro/djangoproject/IDC/datalabel/dboperations.py", line 49, in get_table
    cur.execute(f"""SELECT * from {tableName}""")
sqlite3.OperationalError: no such table: test
2020-07-13 21:34:52,794:ERROR:Database connection error
2020-07-13 21:34:52,859:ERROR:Internal Server Error: /datalabel/labelingProject/IDC
Traceback (most recent call last):
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/shiro/djangoproject/IDC/datalabel/views.py", line 43, in labelingProject
    qTable, categoryList = get_table(tableName=projectName)
  File "/home/shiro/djangoproject/IDC/datalabel/dboperations.py", line 15, in with_connection_
    rv = func(conn, *args, **kwargs)
  File "/home/shiro/djangoproject/IDC/datalabel/dboperations.py", line 55, in get_table
    WHERE projectName = {tableName}""")
sqlite3.OperationalError: no such table: requestForm
2020-07-13 21:35:15,899:ERROR:Database connection error
2020-07-13 21:35:15,954:ERROR:Internal Server Error: /datalabel/labelingProject/darren
Traceback (most recent call last):
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/shiro/djangoproject/IDC/datalabel/views.py", line 43, in labelingProject
    qTable, categoryList = get_table(tableName=projectName)
  File "/home/shiro/djangoproject/IDC/datalabel/dboperations.py", line 15, in with_connection_
    rv = func(conn, *args, **kwargs)
  File "/home/shiro/djangoproject/IDC/datalabel/dboperations.py", line 55, in get_table
    WHERE projectName = {tableName}""")
sqlite3.OperationalError: no such table: requestForm
2020-07-13 21:39:04,122:ERROR:Database connection error
2020-07-13 21:39:04,201:ERROR:Internal Server Error: /datalabel/labelingProject/darren
Traceback (most recent call last):
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/shiro/djangoproject/IDC/datalabel/views.py", line 43, in labelingProject
    qTable, categoryList = get_table(tableName=projectName)
  File "/home/shiro/djangoproject/IDC/datalabel/dboperations.py", line 15, in with_connection_
    rv = func(conn, *args, **kwargs)
  File "/home/shiro/djangoproject/IDC/datalabel/dboperations.py", line 55, in get_table
    WHERE projectName = {tableName}""")
sqlite3.OperationalError: no such column: darren
2020-07-13 21:40:41,163:INFO:/home/shiro/djangoproject/IDC/datalabel/dboperations.py changed, reloading.
2020-07-13 21:40:46,722:ERROR:Database connection error
2020-07-13 21:40:46,805:ERROR:Internal Server Error: /datalabel/labelingProject/darren
Traceback (most recent call last):
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/shiro/djangoproject/IDC/datalabel/views.py", line 43, in labelingProject
    qTable, categoryList = get_table(tableName=projectName)
  File "/home/shiro/djangoproject/IDC/datalabel/dboperations.py", line 15, in with_connection_
    rv = func(conn, *args, **kwargs)
  File "/home/shiro/djangoproject/IDC/datalabel/dboperations.py", line 55, in get_table
    WHERE projectName={tableName}""")
sqlite3.OperationalError: no such column: darren
2020-07-13 21:41:02,576:ERROR:Database connection error
2020-07-13 21:41:02,632:ERROR:Internal Server Error: /datalabel/labelingProject/IDC
Traceback (most recent call last):
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/shiro/djangoproject/IDC/datalabel/views.py", line 43, in labelingProject
    qTable, categoryList = get_table(tableName=projectName)
  File "/home/shiro/djangoproject/IDC/datalabel/dboperations.py", line 15, in with_connection_
    rv = func(conn, *args, **kwargs)
  File "/home/shiro/djangoproject/IDC/datalabel/dboperations.py", line 55, in get_table
    WHERE projectName={tableName}""")
sqlite3.OperationalError: no such column: IDC
2020-07-13 21:42:48,432:INFO:/home/shiro/djangoproject/IDC/datalabel/dboperations.py changed, reloading.
2020-07-13 21:42:51,024:ERROR:Internal Server Error: /datalabel/labelingProject/IDC
Traceback (most recent call last):
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/shiro/djangoproject/IDC/datalabel/views.py", line 49, in labelingProject
    pageObj = pageObj.to_json
AttributeError: 'Page' object has no attribute 'to_json'
2020-07-13 21:43:10,658:INFO:/home/shiro/djangoproject/IDC/datalabel/views.py changed, reloading.
2020-07-13 21:45:38,453:INFO:/home/shiro/djangoproject/IDC/datalabel/views.py changed, reloading.
2020-07-13 21:49:23,062:INFO:/home/shiro/djangoproject/IDC/datalabel/views.py changed, reloading.
2020-07-13 21:49:36,982:WARNING:Not Found: /favicon.ico
2020-07-13 21:50:13,487:WARNING:Not Found: /favicon.ico
2020-07-13 21:50:56,176:WARNING:Not Found: /favicon.ico
2020-07-13 21:59:07,834:INFO:/home/shiro/djangoproject/IDC/datalabel/dboperations.py changed, reloading.
2020-07-13 21:59:10,440:INFO:/home/shiro/djangoproject/IDC/datalabel/dboperations.py changed, reloading.
2020-07-13 21:59:25,942:WARNING:Not Found: /favicon.ico
2020-07-13 22:34:22,508:WARNING:Not Found: /favicon.ico
2020-07-13 22:34:47,470:WARNING:Not Found: /favicon.ico
2020-07-22 22:38:15,109:WARNING:Not Found: /
2020-07-22 22:38:15,730:WARNING:Not Found: /favicon.ico
2020-07-22 22:38:45,930:ERROR:Internal Server Error: /datalabel/labelingProject/IDCtest
Traceback (most recent call last):
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/shiro/djangoproject/IDC/datalabel/views.py", line 53, in labelingProject
    'tableName': tableName
NameError: name 'tableName' is not defined
2020-07-22 22:41:42,769:INFO:/home/shiro/djangoproject/IDC/datalabel/views.py changed, reloading.
2020-07-22 22:41:50,630:ERROR:Internal Server Error: /datalabel/labelingProject/IDCtest
Traceback (most recent call last):
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/shiro/djangoproject/IDC/datalabel/views.py", line 56, in labelingProject
    return render(request, 'datalabel/labelingProject.html', context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/urls/resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'datalabel-labelItem' not found. 'datalabel-labelItem' is not a valid view function or pattern name.
2020-07-22 22:43:16,363:INFO:/home/shiro/djangoproject/IDC/datalabel/urls.py changed, reloading.
2020-07-22 22:43:50,329:INFO:/home/shiro/djangoproject/IDC/datalabel/views.py changed, reloading.
2020-07-22 22:43:55,161:ERROR:Internal Server Error: /datalabel/labelingProject/IDCtest
Traceback (most recent call last):
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/shiro/djangoproject/IDC/datalabel/views.py", line 56, in labelingProject
    return render(request, 'datalabel/labelingProject.html', context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/urls/resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'datalabel-labelItem' with arguments '('Shinya_Kogami_3.webp', 'IDCtest')' not found. 1 pattern(s) tried: ['datalabel\\/labelItem\\/(?P<projectName>[^/]+)$']
2020-07-22 23:05:11,612:INFO:/home/shiro/djangoproject/IDC/datalabel/views.py changed, reloading.
2020-07-22 23:10:05,178:ERROR:Internal Server Error: /datalabel/labelingProject/IDCtest
Traceback (most recent call last):
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/shiro/djangoproject/IDC/datalabel/views.py", line 56, in labelingProject
    return render(request, 'datalabel/labelingProject.html', context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/defaulttags.py", line 443, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/urls/resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'datalabel-labelItem' with keyword arguments '{'arg1': 'Shinya_Kogami_3.webp', 'arg2': 'IDCtest'}' not found. 1 pattern(s) tried: ['datalabel\\/labelItem\\/(?P<projectName>[^/]+)$']
2020-07-22 23:10:05,607:WARNING:Not Found: /favicon.ico
2020-07-22 23:13:43,358:INFO:/home/shiro/djangoproject/IDC/datalabel/urls.py changed, reloading.
2020-07-22 23:13:51,173:WARNING:Not Found: /favicon.ico
2020-07-22 23:14:38,732:WARNING:Not Found: /favicon.ico
2020-07-22 23:14:40,383:ERROR:Internal Server Error: /datalabel/labelItem/IDCtest/Shinya_Kogami_3.webp
Traceback (most recent call last):
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: labelItem() got an unexpected keyword argument 'pname'
2020-07-22 23:15:10,043:INFO:/home/shiro/djangoproject/IDC/datalabel/views.py changed, reloading.
2020-07-22 23:15:14,468:ERROR:Internal Server Error: /datalabel/labelItem/IDCtest/Shinya_Kogami_3.webp
Traceback (most recent call last):
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view datalabel.views.labelItem didn't return an HttpResponse object. It returned None instead.
2020-07-22 23:15:37,247:INFO:/home/shiro/djangoproject/IDC/datalabel/views.py changed, reloading.
2020-07-22 23:15:40,878:ERROR:Internal Server Error: /datalabel/labelItem/IDCtest/Shinya_Kogami_3.webp
Traceback (most recent call last):
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/shiro/djangoproject/IDC/datalabel/views.py", line 60, in labelItem
    return render(request, 'done')
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/shiro/djangoproject/lib/python3.6/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: done
2020-07-22 23:15:41,188:WARNING:Not Found: /favicon.ico
